# Generated by Django 2.1.5 on 2019-02-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
    ]
