language: python
python:
- 3.6
services:
- postgresql
- elasticsearch
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
- DJANGO=2.1.5 PGPORT=5433
before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1
- export DJANGO_SETTINGS_MODULE=config.settings.travis
- export PYTHONPATH=$HOME/builds/voto_backend/voto_backend
- PIP_USE_MIRRORS=true
install:
- pip install -r requirements/travis.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE travisci;" -U postgres
- psql -c "CREATE SCHEMA main_site;" -U postgres
- sleep 10
script:
- python manage.py migrate_both
- pytest
deploy:
  provider: heroku
  api_key:
    secure: "e4+JFBN1mKSPFIPQcmhm0Rzk7bkEBRgaPyVfIJk6XhKExLaVFlujeZ+35QKx7AsI09kpjc+L88Q6/xMO1+DM5h9tajA4BLdayUzBfa38XNSaWLEfkNWgWlSC33nvDWo0W2gUvABWefWv7z/59WUNV7dyJJlGNcYukxh3X6xMoOiXNmDd2gwscBW/HCKt1lu0aP6lGR4lNOuiU4zQT5av10E35VNtcjQXHyHqV1xjuaWiakDEiqh3XEa/nWTBMri9s6usgEtS1P+W6Ez8eUgWfa9Lncb2/AVz04lS7AWKLinmjTJ6H3cbh96YOwgyFUuxAbQgqDEVoAy+FLVOakLS1R4GykUznGawW+pSCzB9caJxPC7rqnG62ociqCx1sK4jB0dBkV1AwnDecjiiejs9vyCjeaabfpg36Qk+DUh5Q0JScm1oIopo/7Vzp+eVoqJZZdzEkhXp8kE/qpKCl9N1vkrlzYclK7FHhD4pUQVH6xFsCl85Z5g4eP2GBbtS2CdKAuBEYdN02t8WWmuZ/MI5pswPumfIwdA9DzG8lbOudAKAfcDzcbuuWYGsdEpTpTTtUfDsrbzSJFqkeZ2c6A+SI3Ag4ai/egr+uyB/MYlxEitOUGHPo4+Ni8Xv1pnicOS/GKzCOCszavyPR1SNBojaN8KOAJvbIjVUkg7GbBj9z+8="
  app: v-development
