# Generated by Django 2.1.7 on 2019-02-19 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('images', 'Images'), ('videos', 'Videos'), ('resources', 'Resources')], default='images', max_length=128, verbose_name='Media Type')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Uploaded')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('images', 'Images'), ('videos', 'Videos'), ('resources', 'Resources')], default='images', max_length=128, verbose_name='Media Type')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Uploaded')),
                ('title', models.CharField(blank=True, default=str, max_length=32)),
                ('brief_description', models.CharField(default=str, max_length=128)),
                ('icon', models.CharField(blank=True, default=str, max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('link', models.URLField(blank=True, max_length=2048)),
                ('voting_resource', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('images', 'Images'), ('videos', 'Videos'), ('resources', 'Resources')], default='images', max_length=128, verbose_name='Media Type')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Uploaded')),
                ('title', models.CharField(blank=True, default=str, max_length=32)),
                ('embed_url', models.URLField(blank=True, max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
