# Generated by Django 2.1.7 on 2019-02-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20190219_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, default=str, max_length=2048),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default=str, max_length=2048),
        ),
    ]
