# Generated by Django 2.1.5 on 2019-01-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190128_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icondata',
            name='tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked'),
        ),
        migrations.AlterField(
            model_name='twitterfeed',
            name='tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked'),
        ),
    ]
