# Generated by Django 2.1.7 on 2019-02-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0003_auto_20190219_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alias',
            field=models.CharField(default=str, max_length=64, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Politician'), ('2', 'Business person'), ('3', 'Civilian'), ('4', 'Alcalde'), ('5', 'Ministro'), ('6', 'Presidente'), ('7', 'Vicepresidente'), ('8', 'Concejal'), ('9', 'Representante'), ('10', 'Gobierno'), ('11', 'Magistrado de la CSJ'), ('12', 'Magistrado Tribunal de Cuentas'), ('13', 'Diputado'), ('14', 'Vicealcalde')], max_length=128, null=True, verbose_name='Type'),
        ),
    ]
