# Generated by Django 2.1.7 on 2019-02-19 23:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0004_auto_20190219_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='experience',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
