# Generated by Django 2.1.7 on 2019-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0006_auto_20190220_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='financial_items',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='corruption.FinancialItem'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='laws',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='political.Law'),
        ),
    ]
