# Generated by Django 2.1.7 on 2019-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0007_corruptioncase_laws'),
        ('political', '0012_auto_20190304_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electoralperiod',
            name='financial_items',
        ),
        migrations.RemoveField(
            model_name='electoralperiod',
            name='images',
        ),
        migrations.RemoveField(
            model_name='electoralperiod',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='electoralperiod',
            name='laws',
        ),
        migrations.RemoveField(
            model_name='electoralperiod',
            name='permitted_users',
        ),
        migrations.RemoveField(
            model_name='electoralperiod',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='electoralperiod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electoralperiod',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='controversy',
            name='financial_items',
        ),
        migrations.RemoveField(
            model_name='controversy',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='promise',
            name='individual',
        ),
        migrations.AddField(
            model_name='achievement',
            name='long_description',
            field=models.TextField(blank=True, default='<p></p>', verbose_name='Long Description'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title',
            field=models.CharField(default=str, max_length=2048, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='controversy',
            name='long_description',
            field=models.TextField(blank=True, default='<p></p>', verbose_name='Long Description'),
        ),
        migrations.AddField(
            model_name='controversy',
            name='title',
            field=models.CharField(default=str, max_length=2048, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='individual',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='political.Achievement'),
        ),
        migrations.AddField(
            model_name='individual',
            name='controversies',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='political.Controversy'),
        ),
        migrations.AddField(
            model_name='individual',
            name='promises',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='political.Promise'),
        ),
        migrations.AddField(
            model_name='organization',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='political.Achievement'),
        ),
        migrations.AddField(
            model_name='organization',
            name='controversies',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='political.Controversy'),
        ),
        migrations.AddField(
            model_name='organization',
            name='corruption_cases',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='corruption.CorruptionCase'),
        ),
        migrations.AddField(
            model_name='organization',
            name='informative_snippets',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='corruption.InformativeSnippet'),
        ),
        migrations.AddField(
            model_name='organization',
            name='promises',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='political.Promise'),
        ),
        migrations.AddField(
            model_name='promise',
            name='long_description',
            field=models.TextField(blank=True, default='<p></p>', verbose_name='Long Description'),
        ),
        migrations.AddField(
            model_name='promise',
            name='title',
            field=models.CharField(default=str, max_length=2048, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='law',
            name='brief_description',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Brief Description'),
        ),
        migrations.DeleteModel(
            name='ElectoralPeriod',
        ),
    ]
