# Generated by Django 2.1.7 on 2019-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0013_auto_20190304_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='controversy',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='controversy',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='individual',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='individual',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='law',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='law',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='organization',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='promise',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='promise',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
