# Generated by Django 2.1.7 on 2019-03-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0015_auto_20190308_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='date_last_publish',
            new_name='date_last_published',
        ),
        migrations.RenameField(
            model_name='controversy',
            old_name='date_last_publish',
            new_name='date_last_published',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='date_last_publish',
            new_name='date_last_published',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='date_last_publish',
            new_name='date_last_published',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='date_last_publish',
            new_name='date_last_published',
        ),
        migrations.RenameField(
            model_name='promise',
            old_name='date_last_publish',
            new_name='date_last_published',
        ),
    ]
