# Generated by Django 2.1.7 on 2019-03-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0016_auto_20190308_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
        migrations.AlterField(
            model_name='controversy',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
        migrations.AlterField(
            model_name='law',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
    ]
