# Generated by Django 2.1.7 on 2019-03-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0018_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='political.Individual'),
        ),
    ]
