# Generated by Django 2.1.7 on 2019-03-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0020_auto_20190310_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Governmental'), ('2', 'Political Party'), ('3', 'Company'), ('4', 'Organización Sin Fines de Lucro')], max_length=128, null=True, verbose_name='Type'),
        ),
    ]
