# Generated by Django 2.1.7 on 2019-03-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0023_remove_organization_laws'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='laws',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='political.Law'),
        ),
    ]
