# Generated by Django 2.1.7 on 2019-03-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0024_organization_laws'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='laws',
        ),
    ]
