# Generated by Django 2.1.5 on 2019-02-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='total_amount',
            new_name='corruption_related_funds',
        ),
        migrations.AddField(
            model_name='individual',
            name='non_corruption_related_funds',
            field=models.FloatField(blank=True, default=float, null=True),
        ),
    ]
