# Generated by Django 2.1.5 on 2019-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0003_auto_20190208_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controversy',
            options={'verbose_name_plural': 'Controversies'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controversy',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electoralperiod',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='law',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promise',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
