# Generated by Django 2.1.5 on 2019-02-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0005_auto_20190208_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(default=str, max_length=128, verbose_name='Name'),
        ),
    ]
