# Generated by Django 2.1.5 on 2019-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0007_auto_20190209_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default=str, max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
