# Generated by Django 2.1.5 on 2019-02-10 05:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0011_auto_20190209_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='controversy',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='electoralperiod',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='law',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Statistics'),
        ),
        migrations.AlterField(
            model_name='promise',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Statistics'),
        ),
    ]
