# Generated by Django 2.1.5 on 2019-02-10 22:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('political', '0013_auto_20190210_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='achievement',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='political_achievement_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controversy',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='controversy',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='political_controversy_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electoralperiod',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='electoralperiod',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='political_electoralperiod_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individual',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='individual',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='political_individual_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='law',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='law',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='political_law_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='political_organization_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promise',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='promise',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='political_promise_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
