# Generated by Django 2.1.5 on 2019-02-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0014_auto_20190210_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
        migrations.RenameField(
            model_name='controversy',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
        migrations.RenameField(
            model_name='electoralperiod',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
        migrations.RenameField(
            model_name='promise',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
    ]
