# Generated by Django 2.1.5 on 2019-02-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0016_auto_20190215_2234'),
        ('political', '0015_auto_20190215_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='financial_items',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='individuals',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='laws',
        ),
        migrations.AddField(
            model_name='individual',
            name='referenced_financial_items',
            field=models.ManyToManyField(blank=True, related_name='referenced_individuals', to='corruption.FinancialItem'),
        ),
        migrations.AddField(
            model_name='individual',
            name='referenced_individuals',
            field=models.ManyToManyField(blank=True, related_name='_individual_referenced_individuals_+', to='political.Individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='referenced_laws',
            field=models.ManyToManyField(blank=True, related_name='referenced_individuals', to='political.Law'),
        ),
        migrations.AddField(
            model_name='individual',
            name='related_financial_items',
            field=models.ManyToManyField(blank=True, related_name='related_individuals', to='corruption.FinancialItem'),
        ),
        migrations.AddField(
            model_name='individual',
            name='related_individuals',
            field=models.ManyToManyField(blank=True, related_name='_individual_related_individuals_+', to='political.Individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='related_laws',
            field=models.ManyToManyField(blank=True, related_name='related_individuals', to='political.Law'),
        ),
    ]
