# Generated by Django 2.1.5 on 2019-02-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0016_auto_20190215_2234'),
        ('political', '0016_auto_20190216_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='referenced_financial_items',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='referenced_individuals',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='referenced_laws',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='related_financial_items',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='related_individuals',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='related_laws',
        ),
        migrations.AddField(
            model_name='individual',
            name='financial_items',
            field=models.ManyToManyField(blank=True, to='corruption.FinancialItem'),
        ),
        migrations.AddField(
            model_name='individual',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='_individual_individuals_+', to='political.Individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='laws',
            field=models.ManyToManyField(blank=True, to='political.Law'),
        ),
    ]
