# Generated by Django 2.1.5 on 2019-02-16 02:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import voto_backend.changes.models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0017_auto_20190216_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
        migrations.AddField(
            model_name='controversy',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
        migrations.AddField(
            model_name='electoralperiod',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
        migrations.AddField(
            model_name='individual',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
        migrations.AddField(
            model_name='law',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
        migrations.AddField(
            model_name='organization',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
        migrations.AddField(
            model_name='promise',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
    ]
