# Generated by Django 2.1.7 on 2019-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('political', '0001_initial'),
        ('media', '0001_initial'),
        ('corruption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativesnippet',
            name='controversies',
            field=models.ManyToManyField(blank=True, related_name='informative_snippets', to='political.Controversy'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='corruption_cases',
            field=models.ManyToManyField(blank=True, related_name='informative_snippets', to='corruption.CorruptionCase'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='financial_items',
            field=models.ManyToManyField(blank=True, related_name='informative_snippets', to='corruption.FinancialItem'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='images',
            field=models.ManyToManyField(blank=True, to='media.Image'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='informative_snippets', to='political.Individual'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='laws',
            field=models.ManyToManyField(blank=True, related_name='informative_snippets', to='political.Law'),
        ),
    ]
