# Generated by Django 2.1.7 on 2019-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0008_auto_20190224_1601'),
        ('corruption', '0004_auto_20190220_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='individuals',
            field=models.ManyToManyField(blank=True, related_name='corruption_cases', to='political.Individual'),
        ),
    ]
