# Generated by Django 2.1.7 on 2019-02-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0004_auto_20190216_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptioncase',
            name='controversies',
            field=models.ManyToManyField(blank=True, related_name='corruption_cases', to='political.Controversy'),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='financial_items',
            field=models.ManyToManyField(blank=True, related_name='corruption_cases', to='corruption.FinancialItem'),
        ),
    ]
