# Generated by Django 2.1.7 on 2019-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0005_corruptioncase_individuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='corruption_cases',
            field=models.ManyToManyField(blank=True, related_name='_corruptioncase_corruption_cases_+', to='corruption.CorruptionCase'),
        ),
    ]
