# Generated by Django 2.1.7 on 2019-03-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0009_auto_20190225_2128'),
        ('corruption', '0006_corruptioncase_corruption_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='laws',
            field=models.ManyToManyField(blank=True, related_name='corruption_cases', to='political.Law'),
        ),
    ]
