# Generated by Django 2.1.7 on 2019-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0007_corruptioncase_laws'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='financialitem',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='financialitem',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='last_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Publish Date'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
