# Generated by Django 2.1.7 on 2019-03-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0008_auto_20190308_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corruptioncase',
            old_name='last_publish_date',
            new_name='date_last_publish',
        ),
        migrations.RenameField(
            model_name='financialitem',
            old_name='last_publish_date',
            new_name='date_last_publish',
        ),
        migrations.RenameField(
            model_name='informativesnippet',
            old_name='last_publish_date',
            new_name='date_last_publish',
        ),
    ]
