# Generated by Django 2.1.7 on 2019-03-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0010_auto_20190308_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptioncase',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
        migrations.AlterField(
            model_name='financialitem',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
        migrations.AlterField(
            model_name='informativesnippet',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
    ]
