# Generated by Django 2.1.7 on 2019-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0011_auto_20190309_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialitem',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
