# Generated by Django 2.1.7 on 2019-03-31 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0012_auto_20190310_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialitem',
            name='corruption_related',
        ),
    ]
