# Generated by Django 2.1.7 on 2019-03-12 00:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voto_studio_backend.changes.models
import voto_studio_backend.forms.models
import voto_studio_backend.search.models
import voto_studio_backend.voting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0003_auto_20190226_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions_dict', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Creation')),
                ('tracked', models.BooleanField(default=True, verbose_name='Tracked')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('date_last_published', models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish')),
                ('source', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Source')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_studio_backend.changes.models.Statistics(), null=True, verbose_name='Statistics')),
                ('location_id_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Location Identifier Name')),
                ('location_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Location Identifier')),
                ('views', models.PositiveIntegerField(default=0)),
                ('rels_dict', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Relationships Dictionary')),
                ('order', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_studio_backend.changes.models.get_order_default, verbose_name='Media Content Order')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('summary', models.CharField(blank=True, max_length=140, null=True)),
                ('body', models.TextField(blank=True)),
                ('references', django.contrib.postgres.fields.jsonb.JSONField(default=voto_studio_backend.voting.models.References())),
                ('images', models.ManyToManyField(blank=True, to='media.Image')),
                ('permitted_users', models.ManyToManyField(blank=True, related_name='voting_tutorial_related', to=settings.AUTH_USER_MODEL)),
                ('resources', models.ManyToManyField(blank=True, to='media.Resource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, to='media.Video')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, voto_studio_backend.forms.models.InfoMixin, voto_studio_backend.search.models.IndexingMixin),
        ),
    ]
