# Generated by Django 2.1.7 on 2019-02-19 12:03

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voto_studio_backend.changes.models
import voto_studio_backend.forms.models
import voto_studio_backend.search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_auto_20190216_1433'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions_dict', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Creation')),
                ('tracked', models.BooleanField(default=True, verbose_name='Tracked')),
                ('location_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Location Identifier')),
                ('location_id_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Location Identifier Name')),
                ('source', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Source')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='Statistics')),
                ('rels_dict', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Relationships Dictionary')),
                ('order', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_studio_backend.changes.models.get_order_default, verbose_name='Media Content Order')),
                ('char_field', models.CharField(blank=True, default=str, max_length=128)),
                ('text_field', models.TextField(blank=True, default=str)),
                ('integer_field', models.IntegerField(blank=True, default=int)),
                ('float_field', models.FloatField(blank=True, default=float)),
                ('boolean_field', models.BooleanField(default=False)),
                ('url_field', models.URLField(blank=True, default=str)),
                ('choice_field', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], max_length=128, null=True)),
                ('date_time_field', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('foreign_key_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_models', to='test_app.BasicModel')),
                ('images', models.ManyToManyField(blank=True, to='media.Image')),
                ('many_to_many_field', models.ManyToManyField(related_name='_basicmodel_many_to_many_field_+', to='test_app.BasicModel')),
                ('one_to_one_field', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.BasicModel')),
                ('permitted_users', models.ManyToManyField(blank=True, related_name='test_app_basicmodel_related', to=settings.AUTH_USER_MODEL)),
                ('resources', models.ManyToManyField(blank=True, to='media.Resource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, to='media.Video')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, voto_studio_backend.forms.models.InfoMixin, voto_studio_backend.search.models.IndexingMixin),
        ),
    ]
