# Generated by Django 2.0.10 on 2019-01-28 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voto_backend.forms.models
import voto_backend.search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation')),
                ('tracked', models.BooleanField(default=True, verbose_name='Whether the instance is tracked')),
                ('char_field', models.CharField(blank=True, default=str, max_length=128)),
                ('text_field', models.TextField(blank=True, default=str)),
                ('integer_field', models.IntegerField(blank=True, default=int)),
                ('float_field', models.FloatField(blank=True, default=float)),
                ('boolean_field', models.BooleanField(default=False)),
                ('url_field', models.URLField(blank=True, default=str)),
                ('choice_field', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], max_length=128, null=True)),
                ('date_time_field', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('foreign_key_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_models', to='test_app.BasicModel')),
                ('many_to_many_field', models.ManyToManyField(related_name='_basicmodel_many_to_many_field_+', to='test_app.BasicModel')),
                ('one_to_one_field', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.BasicModel')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, voto_backend.forms.models.InfoMixin, voto_backend.search.models.IndexingMixin),
        ),
    ]
