# Generated by Django 2.1.7 on 2019-03-09 02:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import voto_studio_backend.changes.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='date_last_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Last Publish'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_studio_backend.changes.models.Statistics(), null=True, verbose_name='Statistics'),
        ),
    ]
