# Generated by Django 2.1.5 on 2019-02-08 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_basicmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='location_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Location Identifier'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='location_id_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Location Identifier Name'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='basicmodel',
            name='tracked',
            field=models.BooleanField(default=True, verbose_name='Tracked'),
        ),
    ]
