# Generated by Django 2.1.7 on 2019-03-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20190309_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
