# Generated by Django 2.1.5 on 2019-02-08 19:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import voto_backend.changes.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20190208_1723'),
        ('test_app', '0003_auto_20190208_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='images',
            field=models.ManyToManyField(blank=True, to='media.Image'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_order_default, verbose_name='Media Content Order'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='resources',
            field=models.ManyToManyField(blank=True, to='media.Resource'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='source',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Statistics'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='videos',
            field=models.ManyToManyField(blank=True, to='media.Video'),
        ),
    ]
