# Generated by Django 2.1.5 on 2019-02-06 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20190206_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='embed_url_src',
        ),
        migrations.AddField(
            model_name='resource',
            name='brief_description',
            field=models.CharField(default=str, max_length=128),
        ),
        migrations.AddField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='icon',
            field=models.CharField(blank=True, default=str, max_length=32),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, default=str, max_length=32),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, default=str, max_length=32),
        ),
    ]
