# Generated by Django 2.1.5 on 2019-02-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20190206_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location_id_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tracked',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='location_id_name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tracked',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='video',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='location_id_name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tracked',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
