# Generated by Django 2.1.5 on 2019-02-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_image_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
