# Generated by Django 2.1.5 on 2019-02-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_resource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
