# Generated by Django 2.1.5 on 2019-02-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20190207_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
    ]
