# Generated by Django 2.1.5 on 2019-02-08 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20190207_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('images', 'Images'), ('videos', 'Videos'), ('resources', 'Resources')], default='images', max_length=128, verbose_name='Media Type'),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('images', 'Images'), ('videos', 'Videos'), ('resources', 'Resources')], default='images', max_length=128, verbose_name='Media Type'),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('images', 'Images'), ('videos', 'Videos'), ('resources', 'Resources')], default='images', max_length=128, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Uploaded'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Uploaded'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Uploaded'),
        ),
    ]
