# Generated by Django 2.1.7 on 2019-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometry',
            name='location_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='geometry',
            name='location_id_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
