# Generated by Django 2.1.5 on 2019-02-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('corruption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativesnippet',
            name='images',
            field=models.ManyToManyField(blank=True, to='media.Image'),
        ),
    ]
