# Generated by Django 2.1.5 on 2019-02-06 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corruption', '0002_informativesnippet_images'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='informativesnippet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='videos',
            field=models.ManyToManyField(blank=True, to='media.Video'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='images',
            field=models.ManyToManyField(blank=True, to='media.Image'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='videos',
            field=models.ManyToManyField(blank=True, to='media.Video'),
        ),
    ]
