# Generated by Django 2.1.5 on 2019-02-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_resource_link'),
        ('corruption', '0003_auto_20190206_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='resources',
            field=models.ManyToManyField(blank=True, to='media.Resource'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='resources',
            field=models.ManyToManyField(blank=True, to='media.Resource'),
        ),
    ]
