# Generated by Django 2.1.5 on 2019-02-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0004_auto_20190207_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='primary_image_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='primary_image_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
