# Generated by Django 2.1.5 on 2019-02-07 19:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0005_auto_20190207_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Media Content Order'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Media Content Order'),
        ),
    ]
