# Generated by Django 2.1.5 on 2019-02-08 01:32

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import voto_backend.changes.models
import voto_backend.forms.models
import voto_backend.search.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0010_auto_20190207_1933'),
        ('corruption', '0006_auto_20190207_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Creation')),
                ('tracked', models.BooleanField(default=True, verbose_name='Tracked')),
                ('location_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Location Identifier')),
                ('location_id_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Location Identifier Name')),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Statistics')),
                ('primary_image_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_order_default, verbose_name='Media Content Order')),
                ('title', models.CharField(default=str, max_length=64, verbose_name='Title')),
                ('brief_description', models.CharField(blank=True, max_length=140, null=True, verbose_name='Description')),
                ('amount', models.FloatField(blank=True, default=float, verbose_name='Amount')),
                ('corruption_related', models.BooleanField(default=False)),
                ('source', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Source')),
                ('images', models.ManyToManyField(blank=True, to='media.Image')),
                ('resources', models.ManyToManyField(blank=True, to='media.Resource')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(blank=True, to='media.Video')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, voto_backend.forms.models.InfoMixin, voto_backend.search.models.IndexingMixin),
        ),
        migrations.AlterField(
            model_name='corruptioncase',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_order_default, verbose_name='Media Content Order'),
        ),
        migrations.AlterField(
            model_name='informativesnippet',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_order_default, verbose_name='Media Content Order'),
        ),
        migrations.AlterField(
            model_name='informativesnippet',
            name='source',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='financial_items',
            field=models.ManyToManyField(blank=True, to='corruption.FinancialItem'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='financial_items',
            field=models.ManyToManyField(blank=True, to='corruption.FinancialItem'),
        ),
    ]
