# Generated by Django 2.1.5 on 2019-02-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0008_auto_20190208_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='images',
        ),
        migrations.RemoveField(
            model_name='law',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='law',
            name='user',
        ),
        migrations.RemoveField(
            model_name='law',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Law',
        ),
    ]
