# Generated by Django 2.1.5 on 2019-02-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political', '0002_auto_20190208_0246'),
        ('corruption', '0009_auto_20190208_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='controversies',
            field=models.ManyToManyField(blank=True, to='political.Controversy'),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialitem',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='controversies',
            field=models.ManyToManyField(blank=True, to='political.Controversy'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='individuals',
            field=models.ManyToManyField(blank=True, to='political.Individual'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='law',
            field=models.ManyToManyField(blank=True, to='political.Law'),
        ),
    ]
