# Generated by Django 2.1.5 on 2019-02-10 22:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corruption', '0014_auto_20190210_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='corruptioncase',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='corruption_corruptioncase_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialitem',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='financialitem',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='corruption_financialitem_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='permission_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='corruption_informativesnippet_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
