# Generated by Django 2.1.5 on 2019-02-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0015_auto_20190210_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corruptioncase',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
        migrations.RenameField(
            model_name='financialitem',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
        migrations.RenameField(
            model_name='informativesnippet',
            old_name='permission_dict',
            new_name='permissions_dict',
        ),
    ]
