# Generated by Django 2.1.5 on 2019-02-16 02:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import voto_backend.changes.models


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0016_auto_20190215_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='corruptioncase',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
        migrations.AddField(
            model_name='financialitem',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
        migrations.AddField(
            model_name='informativesnippet',
            name='rels_dict',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=voto_backend.changes.models.get_rels_dict_default, verbose_name='Relationships Dictionary'),
        ),
    ]
