# Generated by Django 2.1.5 on 2019-02-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corruption', '0017_auto_20190216_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informativesnippet',
            old_name='law',
            new_name='laws',
        ),
    ]
